language: python
python:
  - "3.6"
before_install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
before_script:
  - script/cibuild
script:
  - python -m pytest
services:
  - postgresql
env:
  - FLASK_ENV=ci
