version: '3'

services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fundz
    ports:
      - "5432:5432"
  backend:
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URI=postgres://postgres:postgres@db/fundz
      - DEBUG=True
    links:
      - "db:db"
    ports:
      - "8081:80"
