"""empty message

Revision ID: 464c56bfb2d3
Revises: 
Create Date: 2018-05-31 15:41:59.698801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464c56bfb2d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_order')
    # ### end Alembic commands ###
