"""Add PENumber model

Revision ID: aae012d5f07e
Revises: 464c56bfb2d3
Create Date: 2018-07-09 10:14:23.080549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae012d5f07e'
down_revision = '464c56bfb2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pe_number',
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pe_number')
    # ### end Alembic commands ###
