#!/bin/bash

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

createdb fundz || echo 'Database already exists; skipping'

# Install pipenv
if [ -n "$CI" ]; then
  pip install pipenv
else
  pip install -q pipenv --user
fi
pipenv --python 3.6

# Install application dependencies
script/bootstrap

pipenv run alembic upgrade head
pipenv run python script/ingest_pe_numbers.py
