#!/bin/bash

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

# Update dependencies
script/bootstrap

pipenv run alembic upgrade head
pipenv run python script/ingest_pe_numbers.py
